# /etc/nginx/sites-available/be.dev.storymate.site

log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                  '$status $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" "$http_x_forwarded_for"';

keepalive_timeout   65;

server {
    server_name  be.dev.storymate.site;
    root         /usr/share/nginx/html;

    access_log   /var/log/nginx/proxy/access.log;
    error_log    /var/log/nginx/proxy/error.log;

		##
    # WebSocket 관련 설정
    ##

    location /chat/ {
        proxy_pass http://localhost:8080; # Spring Boot 서버 주소
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        # 캐시 우회를 위한 설정
        proxy_cache_bypass $http_upgrade;

        # CORS 헤더
        add_header 'Access-Control-Allow-Origin' 'http://localhost:3000';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PATCH, OPTIONS, PUT, DELETE';
        add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
        add_header 'Access-Control-Allow-Credentials' 'true';

        # Preflight OPTIONS 요청 처리
        if ($request_method = 'OPTIONS') {
            return 204;
        }
    }

		##
    # 일반 API 요청 처리
    ##

    location / {
        include /etc/nginx/proxy_params;
        proxy_pass http://localhost:8080;

        # CORS 설정
        add_header 'Access-Control-Allow-Origin' 'http://localhost:3000';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PATCH, OPTIONS, PUT, DELETE';
        add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
        add_header 'Access-Control-Allow-Credentials' 'true';

        # OPTIONS 요청 처리
        if ($request_method = 'OPTIONS') {
            return 204;
        }
    }

		##
		# SSL 설정
		##

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/be.dev.storymate.site/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/be.dev.storymate.site/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

##
# HTTP -> HTTPS 리다이렉트
##
server {
    if ($host = be.dev.storymate.site) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

        listen 80 ;
        listen [::]:80 ;
    server_name be.dev.storymate.site;
    return 404; # managed by Certbot
}