services:
  api:
    container_name: storymate-api
    image: storymate/be:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - ACCESS_TOKEN_EXPIRATION_TIME=${ACCESS_TOKEN_EXPIRATION_TIME}
      - REFRESH_TOKEN_EXPIRATION_TIME=${REFRESH_TOKEN_EXPIRATION_TIME}
      - OAUTH_KAKAO_REST_API_KEY=${OAUTH_KAKAO_REST_API_KEY}
      - OAUTH_KAKAO_REDIRECT_URL=${OAUTH_KAKAO_REDIRECT_URL}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}
      - TEST_DATABASE_USERNAME=${TEST_DATABASE_USERNAME}
      - TEST_DATABASE_PASSWORD=${TEST_DATABASE_PASSWORD}
      - AI_CHARACTERS_API=${AI_CHARACTERS_API}
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DEV_SERVER_URL=${DEV_SERVER_URL}
      - KAKAO_PAY_SECRET_KEY=${KAKAO_PAY_SECRET_KEY}
      - KAKAO_PAY_APPROVAL_URL=${KAKAO_PAY_APPROVAL_URL}
      - KAKAO_PAY_CANCEL_URL=${KAKAO_PAY_CANCEL_URL}
      - KAKAO_PAY_FAIL_URL=${KAKAO_PAY_FAIL_URL}
    networks:
      - db-connection

networks:
  db-connection:
    external: true