spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET}
  refresh-token-secret: ${JWT_REFRESH_TOKEN_SECRET}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}

server:
  url: ${PROD_SERVER_URL}
  tomcat:
    keep-alive-timeout: 15m

ai:
  characters: ${AI_CHARACTERS_API}

reading:
  completion:
    threshold: 98

kakao-pay:
  secret-key: ${KAKAO_PAY_SECRET_KEY}
  cid: TC0ONETIME
  approval_url: ${KAKAO_PAY_APPROVAL_URL}
  cancel_url: ${KAKAO_PAY_CANCEL_URL}
  fail_url: ${KAKAO_PAY_FAIL_URL}