spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: ${JWT_ACCESS_TOKEN_SECRET}
token:
  expire:
    time:
      access: ${ACCESS_TOKEN_EXPIRATION_TIME}
      refresh: ${REFRESH_TOKEN_EXPIRATION_TIME}

oauth:
  kakao:
    rest-api-key: ${OAUTH_KAKAO_REST_API_KEY}
    redirect-url: ${OAUTH_KAKAO_REDIRECT_URL}

server:
  url: http://localhost:8080

ai:
  characters: ${AI_CHARACTERS_API}